//! Error types

use num_derive::FromPrimitive;
use solana_program::{decode_error::DecodeError, program_error::ProgramError};
use thiserror::Error;

/// Errors that may be returned by the Token program.
#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum VisionError {
    /// The program address provided doesn't match the value generated by the program.
    #[error("Invalid program address generated from bump seed and key")]
    InvalidProgramAddress,

    /// The account cannot be initialized because it is already being used.
    #[error("Swap account already in use")]
    AlreadyInUse,
    
    // Invalid instruction number passed in.
    #[error("Invalid instruction")]
    InvalidInstruction,

    // Invalid pda associated token address
    #[error("Invalid pda associated token address")]
    InvalidAssociatedPdaTokenAddress,

    // Invalid pda associated token address
    #[error("Invalid swapper associated token address")]
    InvalidAssociatedSwapperTokenAddress,

    // User provided invalid fee account for swap
    #[error("InvalidFeeAccount")]
    InvalidFeeAccount,

    /// Address of the provided swap token account is incorrect.
    #[error("Address of the provided swap token account is incorrect")]
    IncorrectSwapAccount,

    /// Given pool token amount results in zero trading tokens
    #[error("Given pool token amount results in zero trading tokens")]
    ZeroTradingTokens,

    /// Swap instruction exceeds desired slippage limit
    #[error("Swap instruction exceeds desired slippage limit")]
    ExceededSlippage,
    
    /// ConversionFailure
    #[error("Conversion to u64 failed with an overflow or underflow")]
    ConversionFailure,

    /// Operation overflowed
    #[error("Operation overflowed")]
    Overflow,
}
impl From<VisionError> for ProgramError {
    fn from(e: VisionError) -> Self {
        ProgramError::Custom(e as u32)
    }
}
impl<T> DecodeError<T> for VisionError {
    fn type_of() -> &'static str {
        "VisionError"
    }
}
